# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-22 15:48
from __future__ import unicode_literals

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
                ('category_created', models.DateTimeField(auto_now_add=True)),
                ('category_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_item_name', models.CharField(max_length=200)),
                ('category_item_created', models.DateTimeField(auto_now_add=True)),
                ('category_item_modified', models.DateTimeField(auto_now=True)),
                ('category_item_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items', to='excalci.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_name', models.CharField(blank=True, max_length=200, null=True)),
                ('expense_amount', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('expense_mechant_name', models.CharField(blank=True, max_length=200, null=True)),
                ('expense_description', models.TextField(blank=True, null=True)),
                ('expense_created', models.DateTimeField(auto_now_add=True)),
                ('expense_modified', models.DateTimeField(auto_now=True)),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_expenses', to='excalci.Category')),
                ('expense_category_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_items_expenses', to='excalci.CategoryItem')),
                ('expense_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
