# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-29 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excalci', '0002_auto_20180728_1450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('-category_created',)},
        ),
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'ordering': ('-category_item_created',)},
        ),
        migrations.RemoveField(
            model_name='expense',
            name='expense_category',
        ),
        migrations.AlterField(
            model_name='expense',
            name='expense_slug',
            field=models.SlugField(blank=True, max_length=250, null=True, unique_for_date='expense_created'),
        ),
    ]
